/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Frames.EnterName;
import Frames.SelectionFrame;
import Frames.SelectionFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Ezzel
 */

public class Homepage extends javax.swing.JFrame {

    private String playerName;
    
    public String getPlayerName(){
        return playerName;
    }

    /**
     * Creates new form Homepage
     */
    public Homepage(String playerName) {
        initComponents();
        this.playerName = playerName;
        txtPlayerName.setText(playerName); // Set playerName to txtPlayerName
        
        setResizable(false);
        centerFrame();
        lblPlay.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openSelectionFrame();
            }
        });
        
        lblLeaderboards.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openLeaderboards();
            }
        });
        lblPlay1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openSelectionFrame();
            }
        });
        
        lblLeaderboards1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openLeaderboards();
            }
        });
        lblBack.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openEnterName();
            }
        });
    }
    
    private void centerFrame() {
        // Get the screen dimension
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calculate the center position based on the frame size
        int centerX = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int centerY = (int) ((screenSize.getHeight() - getHeight()) / 2);

        // Set the frame location to the center of the screen
        setLocation(centerX, centerY);
    }
    
    
    
    
    private void openSelectionFrame() {
    SelectionFrame selectionFrame = new SelectionFrame(getPlayerName()); // Pass the player's name
    selectionFrame.setVisible(true);
    this.setVisible(false);
}
    
    private void openLeaderboards() {
        leaderboard leaderboardFrame = new leaderboard();
        leaderboardFrame.setVisible(true);
        this.setVisible(false);
    }
    
    private void openEnterName() {
        EnterName en = new EnterName();
        en.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSkull = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        lblBack = new javax.swing.JLabel();
        lblBackbtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlay1 = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        lblLeaderboards1 = new javax.swing.JLabel();
        lblLeaderboards = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSkull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skull.png"))); // NOI18N
        getContentPane().add(lblSkull, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        txtPlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 50));

        lblBack.setFont(new java.awt.Font("Agency FB", 3, 30)); // NOI18N
        lblBack.setForeground(new java.awt.Color(153, 0, 51));
        lblBack.setText("Change User");
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 270, 60));

        lblBackbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        getContentPane().add(lblBackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, 80));

        lblPlay1.setFont(new java.awt.Font("Agency FB", 3, 36)); // NOI18N
        lblPlay1.setText("PLAY");
        getContentPane().add(lblPlay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 70, 60));

        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        getContentPane().add(lblPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 210, 130));

        lblLeaderboards1.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        lblLeaderboards1.setText("LEADERBOARDS");
        getContentPane().add(lblLeaderboards1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 130, 70));

        lblLeaderboards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        getContentPane().add(lblLeaderboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RainMap.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // Get the entered player name
    LeaderboardClass lb = new LeaderboardClass();  
    String playerName = txtPlayerName.getText();
    
    // Insert the player name into the leaderboard
    lb.addPlayer(playerName);
    
    // Update the player name in the frame
    this.playerName = playerName;
        
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void insertNameIntoLeaderboard(String name) {
    try {
        // Establish connection to the database
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fotc_db", "root", "");
        
        // Prepare the SQL statement to insert the name
        String sql = "INSERT INTO leaderboard (username, highest_stage) VALUES (?, 0)";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setString(1, name);
        
        // Execute the SQL statement
        int rowsInserted = statement.executeUpdate();
        if (rowsInserted > 0) {
            System.out.println("A new user has been inserted into the leaderboard.");
        }
        
        // Close the connection
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String defaultPlayerName = ""; 
                new Homepage(defaultPlayerName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBackbtn;
    private javax.swing.JLabel lblLeaderboards;
    private javax.swing.JLabel lblLeaderboards1;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblPlay1;
    private javax.swing.JLabel lblSkull;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
